version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
        - ~/apimongo/data:/data/db
    
  app1:
    container_name: apiservice1
    restart: always
    image: api_service_uni
    links:
       - mongo
  
  app2:
    container_name: apiservice2
    restart: always
    image: api_service_uni
    links:
        - mongo
  
  app3:
    container_name: apiservice3
    restart: always
    image: api_service_uni
    links:
       - mongo
  
  loadba:
    container_name: loadbalancer
    restart: always
    image: loadbalancer_uni
    ports:
      - "5050:5050"
    links:
       - app1
       - app2
       - app3
   
    